version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of .NET: 3.1, 6.0
        VARIANT: "6.0"
        # Optional version of Node.js
        NODE_VERSION: "lts/*"

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    networks:
      - back-tier
    
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  web:
    image: nginx:1.23.1
    volumes:
      - ../frontend/build:/usr/share/nginx/html
      - ./nginx:/etc/nginx
    restart: unless-stopped
    # network_mode: service:app
    networks:
      - back-tier
    ports:
      - 8080:8080
      - 8081:8081
    
  pgadmin:
    image: dpage/pgadmin4:6.14
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: default@email.com
      PGADMIN_DEFAULT_PASSWORD: default_password
      PGADMIN_LISTEN_PORT: 8081
      PGADMIN_SERVER_JSON_FILE: /pgadmin/servers.json
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
     - pgadmin-data:/var/lib/pgadmin
     - ./pgadmin:/pgadmin
    # network_mode: service:db
    ports:
      - 8088:8081
    networks:
      - back-tier

  db: 
    image: postgres:14.3
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - back-tier
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      
    # Add "forwardPortsks": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  seq:
    image: datalust/seq:2022.1
    restart: unless-stopped
    volumes:
      - seq-data:/data
    networks:
      - back-tier
    ports:
      - 8089:80
    environment:
      - ACCEPT_EULA=Y

volumes:
  postgres-data:
  pgadmin-data:
  seq-data:

networks:
  back-tier:
